version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    env_file: .env_docker
    container_name: kingdom
    depends_on:
      - db
    restart: always

  db:
    image: postgres:alpine
    restart: always
    env_file: .env_docker
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: {}