#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {

pg_isready -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -U "${POSTGRES_USER}"
}

until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

DB_NAME="${POSTGRES_DB}"

if ! PGPASSWORD="${POSTGRES_PASSWORD}" psql -h "${POSTGRES_HOST}" -U "${POSTGRES_USER}" -lqt | cut -d \| -f 1 | grep -qw "${DB_NAME}"; then
  >&2 echo "Database ${DB_NAME} does not exist. Creating it now..."
  PGPASSWORD="${POSTGRES_PASSWORD}" psql -h "${POSTGRES_HOST}" -U "${POSTGRES_USER}" -c "CREATE DATABASE ${DB_NAME};"
  >&2 echo "Database ${DB_NAME} created successfully."
else
  >&2 echo "Database ${DB_NAME} already exists."
fi

exec "$@"
