definitions:
  model.Character:
    properties:
      alias:
        type: string
      id:
        type: integer
      lastName:
        type: string
      name:
        type: string
      userID:
        type: integer
    type: object
  model.CharacterClass:
    properties:
      health:
        type: integer
      id:
        type: integer
      name:
        type: string
      perceptionMastery:
        $ref: '#/definitions/model.MasteryLevel'
    type: object
  model.CharacterClassCreate:
    properties:
      health:
        example: 6
        type: integer
      name:
        example: Fighter
        type: string
      perception_mastery:
        example: Train
        type: string
    type: object
  model.CharacterExternal:
    properties:
      alias:
        type: string
      id:
        type: integer
      last_name:
        type: string
      name:
        type: string
      user_id:
        type: integer
    required:
    - name
    type: object
  model.CharacterUpdateExternal:
    properties:
      alias:
        type: string
      last_name:
        type: string
      name:
        type: string
    type: object
  model.CreateCharacter:
    properties:
      alias:
        type: string
      last_name:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  model.CreateUser:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.Domain:
    properties:
      description:
        type: string
      gods:
        items:
          $ref: '#/definitions/model.God'
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
  model.God:
    properties:
      alias:
        type: string
      alignment:
        type: string
      anathema:
        type: string
      areasOfInterest:
        type: string
      chosenWeapon:
        type: string
      description:
        type: string
      domains:
        items:
          $ref: '#/definitions/model.Domain'
        type: array
      edict:
        type: string
      id:
        type: integer
      name:
        type: string
      sacredAnimals:
        type: string
      sacredColors:
        type: string
      temples:
        type: string
      worships:
        type: string
    type: object
  model.MasteryLevel:
    enum:
    - None
    - Train
    - Expert
    - Master
    - Legend
    type: string
    x-enum-varnames:
    - None
    - Train
    - Expert
    - Master
    - Legend
  model.UserExternal:
    properties:
      admin:
        type: boolean
      characters:
        items:
          $ref: '#/definitions/model.Character'
        type: array
      id:
        type: integer
      username:
        type: string
    required:
    - username
    type: object
  model.UserLogin:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.UserPasswordUpdate:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  model.UserUpdateExternal:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Api for Pet Project
  title: Kingdom Api
  version: 0.1.0
paths:
  /character:
    get:
      consumes:
      - application/json
      description: Return all characters for current user
      produces:
      - application/json
      responses:
        "200":
          description: Character details
          schema:
            $ref: '#/definitions/model.CharacterExternal'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Returns all characters
      tags:
      - Character
    post:
      consumes:
      - application/json
      description: Create new character
      parameters:
      - description: Character data
        in: body
        name: character
        required: true
        schema:
          $ref: '#/definitions/model.CreateCharacter'
      produces:
      - application/json
      responses:
        "201":
          description: Character details
          schema:
            $ref: '#/definitions/model.CharacterExternal'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Create and returns character or nil
      tags:
      - Character
  /character/{id}:
    delete:
      consumes:
      - application/json
      description: Permissions for Character's User or Admin
      parameters:
      - description: Character id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "403":
          description: You can't access for this API
          schema:
            type: string
        "404":
          description: Character doesn't exist
          schema:
            type: string
      summary: Deletes Character by ID or returns nil
      tags:
      - Character
    get:
      consumes:
      - application/json
      description: Retrieve Character details using its ID
      parameters:
      - description: character id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: character details
          schema:
            $ref: '#/definitions/model.CharacterExternal'
        "404":
          description: Character not found
          schema:
            type: string
      summary: Returns Character by id
      tags:
      - Character
    patch:
      consumes:
      - application/json
      description: Permissions for Character's User or Admin
      parameters:
      - description: Character id
        in: path
        name: id
        required: true
        type: integer
      - description: Character data
        in: body
        name: character
        required: true
        schema:
          $ref: '#/definitions/model.CharacterUpdateExternal'
      produces:
      - application/json
      responses:
        "200":
          description: Character details
          schema:
            $ref: '#/definitions/model.CharacterExternal'
        "404":
          description: Character doesn't exist
          schema:
            type: string
      summary: Updates Character by ID or nil
      tags:
      - Character
  /class:
    post:
      consumes:
      - application/json
      description: Create new Character Class
      parameters:
      - description: Character Class data
        in: body
        name: god
        required: true
        schema:
          $ref: '#/definitions/model.CharacterClassCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Character Class details
          schema:
            $ref: '#/definitions/model.CharacterClass'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Create and returns new Character Class or nil
      tags:
      - Character Class
  /god:
    post:
      consumes:
      - application/json
      description: Create new God
      parameters:
      - description: God data
        in: body
        name: god
        required: true
        schema:
          $ref: '#/definitions/model.God'
      produces:
      - application/json
      responses:
        "201":
          description: God details
          schema:
            $ref: '#/definitions/model.God'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Create and returns new God or nil
      tags:
      - God
  /god/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve God details using its ID
      parameters:
      - description: god id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: God details
          schema:
            $ref: '#/definitions/model.God'
        "404":
          description: God not found
          schema:
            type: string
      summary: returns God by id
      tags:
      - God
  /login:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя по логину и паролю
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Login user for token
      tags:
      - auth
  /user:
    get:
      consumes:
      - application/json
      description: Returns all users
      produces:
      - application/json
      responses:
        "200":
          description: User list
          schema:
            $ref: '#/definitions/model.UserExternal'
        "500":
          description: Internal Server Error
      summary: Returns all users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: user details
          schema:
            $ref: '#/definitions/model.UserExternal'
        "404":
          description: User already exist
          schema:
            type: string
      summary: Create and returns user or nil
      tags:
      - User
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Ok
          schema:
            type: string
        "400":
          description: User doesn't exist
          schema:
            type: string
        "401":
          description: You need to provide a valid access token or user credentials
            to access this api
          schema:
            type: string
      summary: Returns and delete User by ID if you're admin
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Retrieve User details using its ID
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: user details
          schema:
            $ref: '#/definitions/model.UserExternal'
        "404":
          description: User not found
          schema:
            type: string
      summary: returns User by ID
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Permissions for Admin and current user
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserUpdateExternal'
      produces:
      - application/json
      responses:
        "201":
          description: Ok
          schema:
            type: string
        "400":
          description: User doesn't exist
          schema:
            type: string
        "401":
          description: You need to provide a valid access token or user credentials
            to access this api
          schema:
            type: string
      summary: Update User
      tags:
      - User
  /user/password:
    patch:
      consumes:
      - application/json
      description: 'Permissions: Current User'
      parameters:
      - description: User password data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserPasswordUpdate'
      produces:
      - application/json
      responses:
        "201":
          description: Ok
          schema:
            type: string
        "400":
          description: User doesn't exist
          schema:
            type: string
        "401":
          description: You need to provide a valid access token or user credentials
            to access this api
          schema:
            type: string
      summary: Changes User's password
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  JWT:
    description: JWT security accessToken. Please add it in the format "Bearer {AccessToken}"
      to authorize your requests.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
