definitions:
  model.Character:
    properties:
      alias:
        type: string
      id:
        type: integer
      lastName:
        type: string
      name:
        type: string
      userID:
        type: integer
    type: object
  model.CharacterExternal:
    properties:
      alias:
        type: string
      id:
        type: integer
      last_name:
        type: string
      name:
        type: string
      user_id:
        type: integer
    required:
    - name
    type: object
  model.CreateCharacter:
    properties:
      alias:
        type: string
      last_name:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  model.CreateUser:
    properties:
      admin:
        type: boolean
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.UserExternal:
    properties:
      admin:
        type: boolean
      characters:
        items:
          $ref: '#/definitions/model.Character'
        type: array
      id:
        type: integer
      username:
        type: string
    required:
    - username
    type: object
  model.UserLogin:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
  description: Api for Pet Project
  title: Kingdom Api
  version: 0.1.0
paths:
  /character:
    post:
      consumes:
      - application/json
      description: Create new character
      parameters:
      - description: Character data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateCharacter'
      produces:
      - application/json
      responses:
        "200":
          description: Character details
          schema:
            $ref: '#/definitions/model.CharacterExternal'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Create and returns character or nil
      tags:
      - Character
  /character/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve Character details using its ID
      parameters:
      - description: character id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: character details
          schema:
            $ref: '#/definitions/model.CharacterExternal'
        "404":
          description: Character not found
          schema:
            type: string
      summary: returns Character by id
      tags:
      - Character
  /login:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя по логину и паролю
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Login user for token
      tags:
      - auth
  /user:
    get:
      consumes:
      - application/json
      description: Returns all users
      produces:
      - application/json
      responses:
        "200":
          description: User list
          schema:
            $ref: '#/definitions/model.UserExternal'
        "500":
          description: Internal Server Error
      summary: Returns all users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: user details
          schema:
            $ref: '#/definitions/model.UserExternal'
        "404":
          description: User already exist
          schema:
            type: string
      summary: Create and returns user or nil
      tags:
      - User
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Ok
          schema:
            type: string
        "400":
          description: User doesn't exist
          schema:
            type: string
        "401":
          description: You need to provide a valid access token or user credentials
            to access this api
          schema:
            type: string
      summary: Returns and delete User by ID if you're admin
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Retrieve User details using its ID
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: user details
          schema:
            $ref: '#/definitions/model.UserExternal'
        "404":
          description: User not found
          schema:
            type: string
      summary: returns User by ID
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  JWT:
    description: JWT security accessToken. Please add it in the format "Bearer {AccessToken}"
      to authorize your requests.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
